#include "GLFunctions.h"

#define FUNCTION_ADDRESS(name) \
        name##_gl_type name
#define LOAD_FUNCTION(name) \
        name = reinterpret_cast<name##_gl_type> \
               (GetFunctionAddress(#name, hModule))

namespace White {
namespace Engine {
namespace Graphics {

FUNCTION_ADDRESS(glClear);
FUNCTION_ADDRESS(glClearColor);
FUNCTION_ADDRESS(glCreateShader);
FUNCTION_ADDRESS(glShaderSource);
FUNCTION_ADDRESS(glCompileShader); 
FUNCTION_ADDRESS(glAttachShader);
FUNCTION_ADDRESS(glDetachShader);
FUNCTION_ADDRESS(glDeleteShader);
FUNCTION_ADDRESS(glCreateProgram);
FUNCTION_ADDRESS(glLinkProgram);
FUNCTION_ADDRESS(glUseProgram);
FUNCTION_ADDRESS(glDeleteProgram);
FUNCTION_ADDRESS(glGenBuffers);
FUNCTION_ADDRESS(glBindBuffer);
FUNCTION_ADDRESS(glBufferData);
FUNCTION_ADDRESS(glVertexAttribPointer);
FUNCTION_ADDRESS(glEnableVertexAttribArray);
FUNCTION_ADDRESS(glDisableVertexAttribArray);
FUNCTION_ADDRESS(glBufferSubData);
FUNCTION_ADDRESS(glDeleteBuffers);
FUNCTION_ADDRESS(glDeleteVertexArrays);
FUNCTION_ADDRESS(glGenVertexArrays);
FUNCTION_ADDRESS(glEnable);
FUNCTION_ADDRESS(glCullFace);
FUNCTION_ADDRESS(glFrontFace);
FUNCTION_ADDRESS(glBindVertexArray);
FUNCTION_ADDRESS(glGetShaderiv);
FUNCTION_ADDRESS(glGetProgramiv);
FUNCTION_ADDRESS(glGetBufferSubData);
FUNCTION_ADDRESS(glGetBufferParameteriv);
FUNCTION_ADDRESS(glGetUniformLocation);
FUNCTION_ADDRESS(glUniformMatrix4fv);
FUNCTION_ADDRESS(glProgramUniformMatrix4fv);
FUNCTION_ADDRESS(glGetShaderInfoLog);
FUNCTION_ADDRESS(glGetShaderSource);
FUNCTION_ADDRESS(glGetProgramBinary);
FUNCTION_ADDRESS(glGetProgramInfoLog);
FUNCTION_ADDRESS(glGetError);
FUNCTION_ADDRESS(glDisable);
FUNCTION_ADDRESS(glGenerateMipmap);
FUNCTION_ADDRESS(glUniform1f);
FUNCTION_ADDRESS(glUniform2f);
FUNCTION_ADDRESS(glUniform3f);
FUNCTION_ADDRESS(glUniform4f);     
FUNCTION_ADDRESS(glUniform1i);
FUNCTION_ADDRESS(glUniform2i);
FUNCTION_ADDRESS(glUniform3i);
FUNCTION_ADDRESS(glUniform4i);
FUNCTION_ADDRESS(glUniform1ui);
FUNCTION_ADDRESS(glUniform2ui);
FUNCTION_ADDRESS(glUniform3ui);
FUNCTION_ADDRESS(glUniform4ui);
FUNCTION_ADDRESS(glUniform1fv);
FUNCTION_ADDRESS(glUniform2fv);
FUNCTION_ADDRESS(glUniform3fv);
FUNCTION_ADDRESS(glUniform4fv);
FUNCTION_ADDRESS(glUniform1iv);
FUNCTION_ADDRESS(glUniform2iv);
FUNCTION_ADDRESS(glUniform3iv);
FUNCTION_ADDRESS(glUniform4iv);
FUNCTION_ADDRESS(glUniform1uiv);
FUNCTION_ADDRESS(glUniform2uiv);
FUNCTION_ADDRESS(glUniform3uiv);
FUNCTION_ADDRESS(glUniform4uiv);
FUNCTION_ADDRESS(glUniformMatrix2fv);
FUNCTION_ADDRESS(glUniformMatrix3fv);
FUNCTION_ADDRESS(glUniformMatrix4fv);
FUNCTION_ADDRESS(glUniformMatrix2x3fv); 
FUNCTION_ADDRESS(glUniformMatrix3x2fv);
FUNCTION_ADDRESS(glUniformMatrix2x4fv);
FUNCTION_ADDRESS(glUniformMatrix4x2fv);
FUNCTION_ADDRESS(glUniformMatrix3x4fv);
FUNCTION_ADDRESS(glUniformMatrix4x3fv);
FUNCTION_ADDRESS(glProgramUniform1f);
FUNCTION_ADDRESS(glProgramUniform2f);
FUNCTION_ADDRESS(glProgramUniform3f);
FUNCTION_ADDRESS(glProgramUniform4f);     
FUNCTION_ADDRESS(glProgramUniform1i);
FUNCTION_ADDRESS(glProgramUniform2i);
FUNCTION_ADDRESS(glProgramUniform3i);
FUNCTION_ADDRESS(glProgramUniform4i);
FUNCTION_ADDRESS(glProgramUniform1ui);
FUNCTION_ADDRESS(glProgramUniform2ui);
FUNCTION_ADDRESS(glProgramUniform3ui);
FUNCTION_ADDRESS(glProgramUniform4ui);
FUNCTION_ADDRESS(glProgramUniform1fv);
FUNCTION_ADDRESS(glProgramUniform2fv);
FUNCTION_ADDRESS(glProgramUniform3fv);
FUNCTION_ADDRESS(glProgramUniform4fv);
FUNCTION_ADDRESS(glProgramUniform1iv);
FUNCTION_ADDRESS(glProgramUniform2iv);
FUNCTION_ADDRESS(glProgramUniform3iv);
FUNCTION_ADDRESS(glProgramUniform4iv);
FUNCTION_ADDRESS(glProgramUniform1uiv);
FUNCTION_ADDRESS(glProgramUniform2uiv);
FUNCTION_ADDRESS(glProgramUniform3uiv);
FUNCTION_ADDRESS(glProgramUniform4uiv);
FUNCTION_ADDRESS(glProgramUniformMatrix2fv);
FUNCTION_ADDRESS(glProgramUniformMatrix3fv);
FUNCTION_ADDRESS(glProgramUniformMatrix4fv);
FUNCTION_ADDRESS(glProgramUniformMatrix2x3fv); 
FUNCTION_ADDRESS(glProgramUniformMatrix3x2fv);
FUNCTION_ADDRESS(glProgramUniformMatrix2x4fv);
FUNCTION_ADDRESS(glProgramUniformMatrix4x2fv);
FUNCTION_ADDRESS(glProgramUniformMatrix3x4fv);
FUNCTION_ADDRESS(glProgramUniformMatrix4x3fv);

void* GetFunctionAddress(char* name, HMODULE hModule) {
    PROC address = wglGetProcAddress(name);
    if (!address) {
        address = GetProcAddress(hModule, name);
    }

    return address;
}

void LoadFunctions() {
    HMODULE hModule = LoadLibraryW(L"opengl32.dll");
    LOAD_FUNCTION(glClear);
    LOAD_FUNCTION(glClearColor);
    LOAD_FUNCTION(glCreateShader);
    LOAD_FUNCTION(glShaderSource);
    LOAD_FUNCTION(glCompileShader); 
    LOAD_FUNCTION(glAttachShader);
    LOAD_FUNCTION(glDetachShader);
    LOAD_FUNCTION(glDeleteShader);
    LOAD_FUNCTION(glCreateProgram);
    LOAD_FUNCTION(glLinkProgram);
    LOAD_FUNCTION(glUseProgram);
    LOAD_FUNCTION(glDeleteProgram);
    LOAD_FUNCTION(glGenBuffers);
    LOAD_FUNCTION(glBindBuffer);
    LOAD_FUNCTION(glBufferData);
    LOAD_FUNCTION(glVertexAttribPointer);
    LOAD_FUNCTION(glEnableVertexAttribArray);
    LOAD_FUNCTION(glDisableVertexAttribArray);
    LOAD_FUNCTION(glBufferSubData);
    LOAD_FUNCTION(glDeleteBuffers);
    LOAD_FUNCTION(glDeleteVertexArrays);
    LOAD_FUNCTION(glGenVertexArrays);
    LOAD_FUNCTION(glEnable);
    LOAD_FUNCTION(glCullFace);
    LOAD_FUNCTION(glFrontFace);
    LOAD_FUNCTION(glBindVertexArray);
    LOAD_FUNCTION(glGetShaderiv);
    LOAD_FUNCTION(glGetProgramiv); 
    LOAD_FUNCTION(glGetBufferSubData);
    LOAD_FUNCTION(glGetBufferParameteriv);
    LOAD_FUNCTION(glGetUniformLocation);
    LOAD_FUNCTION(glProgramUniformMatrix4fv);
    LOAD_FUNCTION(glGetShaderiv);
    LOAD_FUNCTION(glGetShaderInfoLog);
    LOAD_FUNCTION(glGetShaderSource);
    LOAD_FUNCTION(glGetProgramBinary);
    LOAD_FUNCTION(glGetProgramInfoLog);
    LOAD_FUNCTION(glGetError);
    LOAD_FUNCTION(glDisable);
    LOAD_FUNCTION(glGenerateMipmap);
    LOAD_FUNCTION(glUniform1f);
    LOAD_FUNCTION(glUniform2f);
    LOAD_FUNCTION(glUniform3f);
    LOAD_FUNCTION(glUniform4f);     
    LOAD_FUNCTION(glUniform1i);
    LOAD_FUNCTION(glUniform2i);
    LOAD_FUNCTION(glUniform3i);
    LOAD_FUNCTION(glUniform4i);
    LOAD_FUNCTION(glUniform1ui);
    LOAD_FUNCTION(glUniform2ui);
    LOAD_FUNCTION(glUniform3ui);
    LOAD_FUNCTION(glUniform4ui);
    LOAD_FUNCTION(glUniform1fv);
    LOAD_FUNCTION(glUniform2fv);
    LOAD_FUNCTION(glUniform3fv);
    LOAD_FUNCTION(glUniform4fv);
    LOAD_FUNCTION(glUniform1iv);
    LOAD_FUNCTION(glUniform2iv);
    LOAD_FUNCTION(glUniform3iv);
    LOAD_FUNCTION(glUniform4iv);
    LOAD_FUNCTION(glUniform1uiv);
    LOAD_FUNCTION(glUniform2uiv);
    LOAD_FUNCTION(glUniform3uiv);
    LOAD_FUNCTION(glUniform4uiv);
    LOAD_FUNCTION(glUniformMatrix2fv);
    LOAD_FUNCTION(glUniformMatrix3fv);
    LOAD_FUNCTION(glUniformMatrix4fv);
    LOAD_FUNCTION(glUniformMatrix2x3fv); 
    LOAD_FUNCTION(glUniformMatrix3x2fv);
    LOAD_FUNCTION(glUniformMatrix2x4fv);
    LOAD_FUNCTION(glUniformMatrix4x2fv);
    LOAD_FUNCTION(glUniformMatrix3x4fv);
    LOAD_FUNCTION(glUniformMatrix4x3fv);
    LOAD_FUNCTION(glProgramUniform1f);
    LOAD_FUNCTION(glProgramUniform2f);
    LOAD_FUNCTION(glProgramUniform3f);
    LOAD_FUNCTION(glProgramUniform4f);     
    LOAD_FUNCTION(glProgramUniform1i);
    LOAD_FUNCTION(glProgramUniform2i);
    LOAD_FUNCTION(glProgramUniform3i);
    LOAD_FUNCTION(glProgramUniform4i);
    LOAD_FUNCTION(glProgramUniform1ui);
    LOAD_FUNCTION(glProgramUniform2ui);
    LOAD_FUNCTION(glProgramUniform3ui);
    LOAD_FUNCTION(glProgramUniform4ui);
    LOAD_FUNCTION(glProgramUniform1fv);
    LOAD_FUNCTION(glProgramUniform2fv);
    LOAD_FUNCTION(glProgramUniform3fv);
    LOAD_FUNCTION(glProgramUniform4fv);
    LOAD_FUNCTION(glProgramUniform1iv);
    LOAD_FUNCTION(glProgramUniform2iv);
    LOAD_FUNCTION(glProgramUniform3iv);
    LOAD_FUNCTION(glProgramUniform4iv);
    LOAD_FUNCTION(glProgramUniform1uiv);
    LOAD_FUNCTION(glProgramUniform2uiv);
    LOAD_FUNCTION(glProgramUniform3uiv);
    LOAD_FUNCTION(glProgramUniform4uiv);
    LOAD_FUNCTION(glProgramUniformMatrix2fv);
    LOAD_FUNCTION(glProgramUniformMatrix3fv);
    LOAD_FUNCTION(glProgramUniformMatrix4fv);
    LOAD_FUNCTION(glProgramUniformMatrix2x3fv); 
    LOAD_FUNCTION(glProgramUniformMatrix3x2fv);
    LOAD_FUNCTION(glProgramUniformMatrix2x4fv);
    LOAD_FUNCTION(glProgramUniformMatrix4x2fv);
    LOAD_FUNCTION(glProgramUniformMatrix3x4fv);
    LOAD_FUNCTION(glProgramUniformMatrix4x3fv);
}

}
}
}
