#pragma once

#include <windows.h>

#include <gl/gl.h>
#include <gl/glext.h>
#include <gl/glcorearb.h>

#define EXTERN_FUNCTION_ADDRESS(type, name) \
        typedef type name##_gl_type; \
        extern name##_gl_type name

namespace White {
namespace Engine {
namespace Graphics {

EXTERN_FUNCTION_ADDRESS(PFNGLCLEARPROC, 
                        glClear);
EXTERN_FUNCTION_ADDRESS(PFNGLCLEARCOLORPROC, 
                        glClearColor);
EXTERN_FUNCTION_ADDRESS(PFNGLCREATESHADERPROC, 
                        glCreateShader);
EXTERN_FUNCTION_ADDRESS(PFNGLSHADERSOURCEPROC, 
                        glShaderSource);
EXTERN_FUNCTION_ADDRESS(PFNGLCOMPILESHADERPROC, 
                        glCompileShader); 
EXTERN_FUNCTION_ADDRESS(PFNGLATTACHSHADERPROC, 
                        glAttachShader);
EXTERN_FUNCTION_ADDRESS(PFNGLDETACHSHADERPROC, 
                        glDetachShader);
EXTERN_FUNCTION_ADDRESS(PFNGLDELETESHADERPROC, 
                        glDeleteShader);
EXTERN_FUNCTION_ADDRESS(PFNGLCREATEPROGRAMPROC, 
                        glCreateProgram);
EXTERN_FUNCTION_ADDRESS(PFNGLLINKPROGRAMPROC, 
                        glLinkProgram);
EXTERN_FUNCTION_ADDRESS(PFNGLUSEPROGRAMPROC, 
                        glUseProgram);
EXTERN_FUNCTION_ADDRESS(PFNGLDELETEPROGRAMPROC, 
                        glDeleteProgram);
EXTERN_FUNCTION_ADDRESS(PFNGLGENBUFFERSPROC, 
                        glGenBuffers);
EXTERN_FUNCTION_ADDRESS(PFNGLBINDBUFFERPROC, 
                        glBindBuffer);
EXTERN_FUNCTION_ADDRESS(PFNGLBUFFERDATAPROC, 
                        glBufferData);
EXTERN_FUNCTION_ADDRESS(PFNGLVERTEXATTRIBPOINTERPROC, 
                        glVertexAttribPointer);
EXTERN_FUNCTION_ADDRESS(PFNGLENABLEVERTEXATTRIBARRAYPROC, 
                        glEnableVertexAttribArray);
EXTERN_FUNCTION_ADDRESS(PFNGLDISABLEVERTEXATTRIBARRAYPROC, 
                        glDisableVertexAttribArray);
EXTERN_FUNCTION_ADDRESS(PFNGLBUFFERSUBDATAPROC, 
                        glBufferSubData);
EXTERN_FUNCTION_ADDRESS(PFNGLDELETEBUFFERSPROC, 
                        glDeleteBuffers);
EXTERN_FUNCTION_ADDRESS(PFNGLDELETEVERTEXARRAYSPROC, 
                        glDeleteVertexArrays);
EXTERN_FUNCTION_ADDRESS(PFNGLGENVERTEXARRAYSPROC, 
                        glGenVertexArrays);
EXTERN_FUNCTION_ADDRESS(PFNGLENABLEPROC, 
                        glEnable);
EXTERN_FUNCTION_ADDRESS(PFNGLCULLFACEPROC, 
                        glCullFace);
EXTERN_FUNCTION_ADDRESS(PFNGLFRONTFACEPROC, 
                        glFrontFace);
EXTERN_FUNCTION_ADDRESS(PFNGLBINDVERTEXARRAYPROC, 
                        glBindVertexArray);
EXTERN_FUNCTION_ADDRESS(PFNGLGETSHADERIVPROC, 
                        glGetShaderiv);
EXTERN_FUNCTION_ADDRESS(PFNGLGETPROGRAMIVPROC, 
                        glGetProgramiv);
EXTERN_FUNCTION_ADDRESS(PFNGLGETBUFFERSUBDATAPROC, 
                        glGetBufferSubData);
EXTERN_FUNCTION_ADDRESS(PFNGLGETBUFFERPARAMETERIVPROC,
                        glGetBufferParameteriv);
EXTERN_FUNCTION_ADDRESS(PFNGLGETUNIFORMLOCATIONPROC, 
                        glGetUniformLocation);
EXTERN_FUNCTION_ADDRESS(PFNGLGETSHADERIVPROC,
                        glGetShaderiv);
EXTERN_FUNCTION_ADDRESS(PFNGLGETSHADERINFOLOGPROC,
                        glGetShaderInfoLog);
EXTERN_FUNCTION_ADDRESS(PFNGLGETSHADERSOURCEPROC,
                        glGetShaderSource);
EXTERN_FUNCTION_ADDRESS(PFNGLGETPROGRAMBINARYPROC,
                        glGetProgramBinary);
EXTERN_FUNCTION_ADDRESS(PFNGLGETPROGRAMINFOLOGPROC,
                        glGetProgramInfoLog);
EXTERN_FUNCTION_ADDRESS(PFNGLGETERRORPROC,
                        glGetError);
EXTERN_FUNCTION_ADDRESS(PFNGLDISABLEPROC,
                        glDisable);
EXTERN_FUNCTION_ADDRESS(PFNGLGENERATEMIPMAPPROC,
                        glGenerateMipmap);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM1FPROC,
                        glUniform1f);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM2FPROC,
                        glUniform2f);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM3FPROC,
                        glUniform3f);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM4FPROC,
                        glUniform4f);     
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM1IPROC,
                        glUniform1i);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM2IPROC,
                        glUniform2i);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM3IPROC,
                        glUniform3i); 
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM4IPROC, 
                        glUniform4i);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM1UIPROC,
                        glUniform1ui);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM2UIPROC,
                        glUniform2ui);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM3UIPROC,
                        glUniform3ui);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM4UIPROC,
                        glUniform4ui);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM1FVPROC,
                        glUniform1fv);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM2FVPROC,
                        glUniform2fv);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM3FVPROC,
                        glUniform3fv);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM4FVPROC,
                        glUniform4fv);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM1IVPROC,
                        glUniform1iv);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM2IVPROC,
                        glUniform2iv);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM3IVPROC,
                        glUniform3iv);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM4IVPROC,
                        glUniform4iv);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM1UIVPROC,
                        glUniform1uiv);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM2UIVPROC,
                        glUniform2uiv);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM3UIVPROC,
                        glUniform3uiv);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORM4UIVPROC,
                        glUniform4uiv);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORMMATRIX2FVPROC,
                        glUniformMatrix2fv);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORMMATRIX3FVPROC,
                        glUniformMatrix3fv);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORMMATRIX4FVPROC,
                        glUniformMatrix4fv);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORMMATRIX2X3FVPROC,
                        glUniformMatrix2x3fv); 
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORMMATRIX3X2FVPROC,
                        glUniformMatrix3x2fv);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORMMATRIX2X4FVPROC,
                        glUniformMatrix2x4fv);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORMMATRIX4X2FVPROC,
                        glUniformMatrix4x2fv);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORMMATRIX3X4FVPROC,
                        glUniformMatrix3x4fv);
EXTERN_FUNCTION_ADDRESS(PFNGLUNIFORMMATRIX4X3FVPROC,
                        glUniformMatrix4x3fv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM1FPROC,
                        glProgramUniform1f);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM2FPROC,
                        glProgramUniform2f);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM3FPROC,
                        glProgramUniform3f);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM4FPROC,
                        glProgramUniform4f);     
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM1IPROC,
                        glProgramUniform1i);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM2IPROC,
                        glProgramUniform2i);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM3IPROC,
                        glProgramUniform3i); 
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM4IPROC, 
                        glProgramUniform4i);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM1UIPROC,
                        glProgramUniform1ui);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM2UIPROC,
                        glProgramUniform2ui);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM3UIPROC,
                        glProgramUniform3ui);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM4UIPROC,
                        glProgramUniform4ui);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM1FVPROC,
                        glProgramUniform1fv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM2FVPROC,
                        glProgramUniform2fv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM3FVPROC,
                        glProgramUniform3fv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM4FVPROC,
                        glProgramUniform4fv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM1IVPROC,
                        glProgramUniform1iv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM2IVPROC,
                        glProgramUniform2iv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM3IVPROC,
                        glProgramUniform3iv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM4IVPROC,
                        glProgramUniform4iv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM1UIVPROC,
                        glProgramUniform1uiv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM2UIVPROC,
                        glProgramUniform2uiv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM3UIVPROC,
                        glProgramUniform3uiv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORM4UIVPROC,
                        glProgramUniform4uiv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORMMATRIX2FVPROC,
                        glProgramUniformMatrix2fv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORMMATRIX3FVPROC,
                        glProgramUniformMatrix3fv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORMMATRIX4FVPROC,
                        glProgramUniformMatrix4fv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC,
                        glProgramUniformMatrix2x3fv); 
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC,
                        glProgramUniformMatrix3x2fv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC,
                        glProgramUniformMatrix2x4fv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC,
                        glProgramUniformMatrix4x2fv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC,
                        glProgramUniformMatrix3x4fv);
EXTERN_FUNCTION_ADDRESS(PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC,
                        glProgramUniformMatrix4x3fv);

void* GetFunctionAddress(char* name, HMODULE hModule);
void LoadFunctions();

}
}
}
